### Get all games
GET https://cse341-boardgameapi.onrender.com/games

### Create a new game
POST https://cse341-boardgameapi.onrender.com/games
Content-Type: application/json

{
    "title": "Ticket to Ride",
    "publisher": "Days of Wonder",
    "yearPublished": 2004,
    "minPlayers": 2,
    "maxPlayers": 5,
    "playTime": 60,
    "complexity": "Light-Medium",
    "genre": "Strategy, Route-Building",
    "description": "Players collect train cards to claim railway routes across a map, connecting cities and completing destination tickets for points."
}


### Get a single game
GET https://cse341-boardgameapi.onrender.com/games/68d539a09abd2a312f714637

### Get a single game
GET https://cse341-boardgameapi.onrender.com/games/68d539a09abd2a312f714638

### Get a single game
GET https://cse341-boardgameapi.onrender.com/games/68d539a09abd2a312f714639

### Update a Game
PUT https://cse341-boardgameapi.onrender.com/games/68d678a026f1607d09bc28af
Content-Type: application/json

{
    "title": "Ticket to Ride",
    "publisher": "Days of Wonder",
    "yearPublished": 2004,
    "minPlayers": 2,
    "maxPlayers": 5,
    "playTime": 60,
    "complexity": "Light-Medium",
    "genre": "Strategy, Route-Building, Train themed",
    "description": "Players collect train cards to claim railway routes across a map, connecting cities and completing destination tickets for points."
}

### Delete a Game
DELETE https://cse341-boardgameapi.onrender.com/games/68d61b0c12748fa297b37ebf HTTP/1.1
