### Get all games
GET https://cse341-boardgameapi.onrender.com/games
Cookie: connect.sid=s%3ARsCcU1Q1PHZHKmyVy3mIOpaVkTGv7_Ij.z7CSWaemuLQyB08A2FYFNhpN3mPmfi38mAK9nc49XO4
Accept: application/json

### Get a single game
GET https://cse341-boardgameapi.onrender.com/games/68d539a09abd2a312f714637
Cookie: connect.sid=s%3ARsCcU1Q1PHZHKmyVy3mIOpaVkTGv7_Ij.z7CSWaemuLQyB08A2FYFNhpN3mPmfi38mAK9nc49XO4
Accept: application/json

### Create a new game
POST https://cse341-boardgameapi.onrender.com/games
Content-Type: application/json
Accept: application/json
Cookie: connect.sid=s%3ARsCcU1Q1PHZHKmyVy3mIOpaVkTGv7_Ij.z7CSWaemuLQyB08A2FYFNhpN3mPmfi38mAK9nc49XO4

{
    "title": "Monopoly",
    "publisher": "Days of Wonder",
    "yearPublished": 2004,
    "minPlayers": 2,
    "maxPlayers": 5,
    "playTime": 60,
    "complexity": "Light-Medium",
    "genre": "Strategy, Route-Building",
    "description": "Players collect train cards to claim railway routes across a map, connecting cities and completing destination tickets for points."
}

### Update a game
PUT https://cse341-boardgameapi.onrender.com/games/68deb9e81aa3d12b25c117b5
Content-Type: application/json
Accept: application/json
Cookie: connect.sid=s%3ARsCcU1Q1PHZHKmyVy3mIOpaVkTGv7_Ij.z7CSWaemuLQyB08A2FYFNhpN3mPmfi38mAK9nc49XO4

{
    "title": "Ticket to Ride Europe",
    "publisher": "Days of Wonder",
    "yearPublished": 2004,
    "minPlayers": 2,
    "maxPlayers": 5,
    "playTime": 60,
    "complexity": "Light-Medium",
    "genre": "Strategy, Route-Building, Train themed",
    "description": "Players collect train cards to claim railway routes across a map, connecting cities and completing destination tickets for points."
}

### Delete a game
DELETE https://cse341-boardgameapi.onrender.com/games/68debad41aa3d12b25c117b6
Cookie: connect.sid=s%3ARsCcU1Q1PHZHKmyVy3mIOpaVkTGv7_Ij.z7CSWaemuLQyB08A2FYFNhpN3mPmfi38mAK9nc49XO4
Accept: application/json
