### Get all users
GET https://cse341-boardgameapi.onrender.com/users

### Create a new game
POST https://cse341-boardgameapi.onrender.com/users
Content-Type: application/json

{
    "username": "Skott",
    "email": "proskott@gmail.com"
}


### Get a single user
GET https://cse341-boardgameapi.onrender.com/users/68d539f99abd2a312f714646

### Update a User
PUT https://cse341-boardgameapi.onrender.com/users/68d66dd82532f9a1f8e3f5e8
Content-Type: application/json

{
    "username": "Jamie",
    "email": "oliver@gmail.com"
}

### Delete a Game
DELETE https://cse341-boardgameapi.onrender.com/users/68dec1fe1d2418257288c9ea 
